services:
  - type: web
    name: malikabdulfarhan
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_PROVIDER
        value: postgres
      - key: POSTGRES_AUTO_MIGRATE
        value: "true"
      - key: POSTGRES_SSL
        value: "true"
      - key: JWT_EXPIRES_IN_SECONDS
        value: "3600"
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
